[package]
name = "rcrypto"
version = "0.1.0"
authors = ["Tino"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rcrypto"
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
cbindgen = "0.15.0"

[dependencies]
rust-crypto = "^0.2"
rustc-serialize = "^0.3"